[package]
name = "kakeibo_6"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.214", features = ["derive"] }
